name: wsl2distromanager
description: A GUI to quickly manage your WSL instances.

publish_to: "none"
version: 1.9.0 # Current version

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  archive: ^4.0.7
  async: ^2.13.0
  chunked_downloader: ^1.0.0
  desktop_window: ^0.4.2
  dio: ^5.9.0
  file_picker: ^10.3.7
  fluent_ui: ^4.13.0
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.4
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.7
  go_router: ^17.0.0
  http: ^1.6.0
  localization: ^2.1.1
  package_info_plus: ^9.0.0
  path: ^1.9.1
  plausible_analytics: ^0.3.0
  provider: ^6.1.5
  re_editor: ^0.8.0
  re_highlight: ^0.0.3
  shared_preferences: ^2.5.3
  shelf: ^1.4.2
  shelf_static: ^1.1.3
  system_info2: ^4.1.0
  system_theme: ^3.1.2
  url_launcher: ^6.3.2
  window_manager: ^0.5.1
  yaml: ^3.1.3
dependency_overrides:
  http: ^1.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_oss_licenses: ^3.0.11
  flutter_test:
    sdk: flutter
  msix: ^3.16.12

flutter:
  uses-material-design: true
  assets:
    - lib/i18n/
    - assets/scripts/settings.bash

msix_config:
  display_name: WSL Manager
  publisher_display_name: Bostrot
  identity_name: 9891PhantomDevs.WSL2Manager
  msix_version: 1.8.2.0
  publisher: CN=94697CA2-9680-453C-A7CB-2FA531A4A341
  logo_path: .\assets\logo_wsl_manager.png
  start_menu_icon_path: .\assets\logo_wsl_manager.png
  tile_icon_path: .\assets\logo_wsl_manager.png
  icons_background_color: transparent
  architecture: x64
  capabilities: internetClient,privateNetworkClientServer,runFullTrust
  store: true
  languages: en-US, en-GB, en-AU, de-DE, pt-BR, pt-PT, zh-CN, zh-TW, tr-TR
