name: wsl2distromanager
description: A GUI to quickly manage your WSL instances.

publish_to: "none"
version: 1.8.15 # Current version

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  archive: ^4.0.2
  async: ^2.11.0
  chunked_downloader: ^0.0.2
  desktop_window: ^0.4.0
  dio: ^5.3.2
  file_picker: ^8.0.3
  fluent_ui: ^4.7.2
  flutter_acrylic: ^1.1.3
  flutter_localization: ^0.3.0
  flutter_markdown: ^0.7.4+1
  go_router: ^14.4.1
  http: ^1.1.0
  localization: ^2.1.0
  package_info_plus: ^8.1.1
  plausible_analytics: ^0.3.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  system_info2: ^4.0.0
  system_theme: ^3.1.2
  url_launcher: ^6.1.12
  window_manager: ^0.4.3
  yaml: ^3.1.2
  re_editor: ^0.6.0
  re_highlight: ^0.0.3
dependency_overrides:
  http: ^1.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_oss_licenses: ^3.0.2
  flutter_test:
    sdk: flutter
  msix: ^3.14.2

flutter:
  uses-material-design: true
  assets:
    - lib/i18n/
    - assets/scripts/settings.bash

msix_config:
  display_name: WSL Manager
  publisher_display_name: Bostrot
  identity_name: 9891PhantomDevs.WSL2Manager
  msix_version: 1.8.2.0
  publisher: CN=94697CA2-9680-453C-A7CB-2FA531A4A341
  logo_path: .\assets\logo_wsl_manager.png
  start_menu_icon_path: .\assets\logo_wsl_manager.png
  tile_icon_path: .\assets\logo_wsl_manager.png
  icons_background_color: transparent
  architecture: x64
  capabilities: "internetClient"
  store: true
  languages: en-US, en-GB, en-AU, de-DE, pt-BR, pt-PT, zh-CN, zh-TW, tr-TR
