name: wsl2distromanager
description: A GUI to quickly manage your WSL instances.

publish_to: 'none'
version: 1.6.1 # Current version

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  localization: ^2.1.0
  desktop_window: ^0.4.0
  fluent_ui: ^4.4.1
  system_theme: ^2.1.0
  file_picker: ^5.0.1
  url_launcher: ^6.1.6
  dio: ^5.0.3
  package_info_plus: ^3.0.2
  plausible_analytics: ^0.2.1
  shared_preferences: ^2.0.15
  shelf_static: ^1.1.1
  shelf: ^1.4.0
  window_manager: ^0.3.0
  provider: ^6.0.3
  flutter_acrylic: ^1.0.0+2
  system_info2: ^3.0.1
  yaml: ^3.1.1
  archive: ^3.3.5
  http: ^0.13.5
  async: ^2.9.0
  chunked_downloader: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^3.7.0
  flutter_lints: ^2.0.1
  flutter_oss_licenses: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/i18n/
    - assets/scripts/settings.bash
